# Basic
title: 重庆鲳鱼
subtitle: xxx
description: 欢迎来到我的博客~
# 头像里面的标题
avatarTitle: 工欲善其事
# 头像里面的描述
avatarDesc: 必先利其器
url: "http://www.cqcyu.cc"

# Comment
comment:
    disqus: changyuet
    # uyan: 2144827  # 有言id,登录有言官网申请

# Social
social:
    weibo: 10180016 
    github: changyuet
    # twitter: 
    mail: 10180016@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 5370680d4e82d0c53afc426673a58645  



# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


